### ISSUE TITLE
support backend1 team WebUntis testing

### ISSUE THREAD

**Issue by CallMeAlasca** [htl-grieskirchen-core/core#145]

**Comment by Klausmd5** [comment]
Error:

`System.Security.Cryptography.CryptographicException: The length of the data to decrypt is not valid for the size of this key.

   at System.Security.Cryptography.RSAImplementation.RSACng.EncryptOrDecrypt(Byte[] data, RSAEncryptionPadding padding, Boolean encrypt)

   at System.Security.Cryptography.RSAImplementation.RSACng.Decrypt(Byte[] data, RSAEncryptionPadding padding)

   at Core.Backend.Secure.Services.CredService.DecryptPw(String pw) in C:\Users\fabian\Documents\syp\core\Core.Backend.Secure\Services\CredService.cs:line 28

   at Core.Backend.Secure.Services.CredService.GetWebUntisSecret(Guid uuid) in C:\Users\fabian\Documents\syp\core\Core.Backend.Secure\Services\CredService.cs:line 25

   at Core.Backend.Secure.Services.WebUntisService.GetWebUntisCredentials(ClaimsPrincipal user) in C:\Users\fabian\Documents\syp\core\Core.Backend.Secure\Services\WebUntisService.cs:line 33

   at Core.Backend.Secure.Services.WebUntisService.GetWebUntisClient(ClaimsPrincipal user) in C:\Users\fabian\Documents\syp\core\Core.Backend.Secure\Services\WebUntisService.cs:line 22

   at Core.Backend.Secure.Services.WebUntisService.GetHolidays(ClaimsPrincipal user) in C:\Users\fabian\Documents\syp\core\Core.Backend.Secure\Services\WebUntisService.cs:line 68

   at Core.Backend.Secure.Controllers.WebUntisController.GetHolidays() in C:\Users\fabian\Documents\syp\core\Core.Backend.Secure\Controllers\WebUntisController.cs:line 43

   at lambda_method8(Closure , Object )

   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)

   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)



HEADERS

=======

Accept: text/plain

Connection: keep-alive

Host: localhost:5152

User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0

Accept-Encoding: gzip, deflate, br

Accept-Language: en-GB,en;q=0.5

Cookie: JSESSIONID=057C8DCE9C96B609DBFB981B62AB69EA; auth=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2IiwidHlwIjoiSldUIn0.eyJ0eXBlIjoiYXV0aC10b2tlbiIsInVzZXJuYW1lIjoiU2Nob2VuYmVyZ2VyRjE4MDA3MyIsInV1aWQiOiI4NzkzZjhiZi0xOWVhLTQ5MjEtOGE4YS1lMzhiZjE3YzdiYjAiLCJleHAiOjE2NzE1MTgxNjcsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCJ9.ElKcrLJi5gUCjjYtwoiTP2KpgZIBXAPEAHred5f2-ovbfDup-Edd5FoP_DniY24ZR-jQ7815UsaOtYr6vFTRG0sacXrLe3zRN6CdSfPrtfqYkVGdbdBB28vy8lsvvVcpDZpftCOIPVI8b1ML_uxkw52dzldpE1wTs9kithnsgRAAOQbY4N3841S-v0PBs87EEwCamkSbGOcWSew-0FbV65SY4K1izT-owrOEjMPKppsnwdQvqLBFf87LLBvR1AJMmdb3NwwfyIXHUlzFDCgfyU9isIULGYLe1wTZ2cQzRFvG1oxt5dN4-jZNc_ge8HjStWgAnsMJgXrLi_0_zeL5LDS_L02V6RgFL7XYWsBr58wxOd7HoPuTWAvoDMDt8UiFAkRbNa5HYyVSkLJ1-kFccAJT18DplkeoL_MXeP22rZ4ljZhcVl4e7lSWpjtXVGvPa7X5kA61bH9CCX2_y4fUJY7JQLvZ13fifVLnkiKCU2n8CNGDP9T_6Y9IqF0APYBA

Referer: http://localhost:5152/swagger/index.html

Sec-Fetch-Dest: empty

Sec-Fetch-Mode: cors

Sec-Fetch-Site: same-origin
`

Resolved: Password was stored in plaintext - so the key is 2 short to decrypt
